spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: liang
        password: liang
        url: jdbc:mysql://localhost:3306/blog_system?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        type: com.alibaba.druid.pool.DruidDataSource
mybatis:
    config-location: classpath:mybatis-config.xml
    mapper-locations: classpath:mapper/**/*.xml
