server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 10
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: mymongo
  management:
    endpoints:
      web:
        exposure:
          include=beans: true
mybatis:
  type-aliases-package: com.liang.blog.po  # 指定MyBatis实体类的包名
  mapper-locations: classpath:mapper/*.xml  # 指定Mapper XML文件的位置，这里假设XML文件放在resources/mapper目录下



logging:
  level:
    root: INFO  # 根日志级别
    org.springframework.web: INFO  # Spring框架日志级别
    com.example: DEBUG  # 您的应用程序包的日志级别，可以根据需要进行调整